name: Exibi valor de uma secret

on:
  workflow_dispatch:

jobs:
  show-ecret:
    runs-on: ubuntu-latest
    steps:
      - name: Tentando expor o valor de uma secret
        run: echo "${{ secrets.GITHUB_TOKEN }}"
        
      - name: Tentando expor secret manipulando a saÂ´da
        run: echo "${{ secrets.GITHUB_TOKEN }}" | sed 's/./& /g'