name: Workflow run

on:
  workflow_run:
    workflows: [Workflow reutilizavel]
    types:
      - completed

jobs:
  exibe-mensagem-tete:
    runs-on: ubuntu-latest
    steps:
      - name: Exibe mensgaem
        run: echo "WKF compartilhado terminal e chamou o WKF run"   
